set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'google/vim-colorscheme-primary'
Plugin 'sheerun/vim-wombat-scheme'
"Plugin 'lodifice/panzer.vim'
Plugin 'udalov/kotlin-vim'
Plugin 'robertbraeutigam/vim-java-tags'
Plugin 'PotatoesMaster/i3-vim-syntax'
Plugin 'chriskempson/base16-vim'
"Plugin 'davidhalter/jedi-vim'

call vundle#end()

execute pathogen#infect()

filetype plugin indent on    " required
syntax on
"set background=dark
colorscheme base16-custom
"colorscheme wombat
let base16colorspace=256
set expandtab       " expand tabs to spaces
set tabstop=4       " each tab is 4 spaces
set shiftwidth=4    " use 4 spaces for each indent level
set shiftround      " orientate indent on shiftwidth
set hlsearch        " always highlight search results
set incsearch       " search incrementally
set ignorecase      " ignore case when searching
set smartcase       " ignore ignorecase when uppercase letter in search string
set background=dark

autocmd FileType java setlocal omnifunc=javacomplete#Complete

set ruler
set scrolloff=2
set colorcolumn=80
set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/
set laststatus=2
set t_Co=256
set number
set relativenumber
set showcmd

function! Attach()
    silent !ranger --choosefiles=/tmp/chosenfiles
    if filereadable('/tmp/chosenfiles')
        call append(6, map(readfile('/tmp/chosenfiles'), '"Attach: ".substitute(v:val,''\s'',''\\ '',"g")'))
        call system('rm /tmp/chosenfiles')
    endif
    redraw!
endfunction

command! ChooseFile :execute "call Attach()"

" neocomplete
